version: '3.8'

services:
  database:
    container_name: "cart-system"
    image: "postgres:16"
    ports:
    - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
  