CREATE TABLE carts (
    id SERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE cart_items DROP COLUMN user_id;

ALTER TABLE cart_items ADD COLUMN cart_id BIGINT NOT NULL REFERENCES carts(id) ON DELETE CASCADE;